SET DEFINE OFF;
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (1, 'TIPO DE PERTURBACION', 'TIPOS DE PERTURBACION', 'C', 'C', 'S', TO_DATE('10/20/2015 10:47:04', 'MM/DD/YYYY HH24:MI:SS'), 'IFN', TO_DATE('10/20/2015 10:47:04', 'MM/DD/YYYY HH24:MI:SS'), 'IFN');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (2, 'SEVERIDAD DE LA PERTURBACION', 'SEVERIDAD DE LA PERTURBACION', 'C', 'C', 'S', TO_DATE('10/20/2015 10:57:09', 'MM/DD/YYYY HH24:MI:SS'), 'IFN', TO_DATE('10/20/2015 10:57:09', 'MM/DD/YYYY HH24:MI:SS'), 'IFN');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (3, 'TIPO DE COBERTURA', 'TIPO DE COBERTURA', 'C', 'C', 'S', TO_DATE('10/20/2015 10:57:09', 'MM/DD/YYYY HH24:MI:SS'), 'IFN', TO_DATE('10/20/2015 10:57:09', 'MM/DD/YYYY HH24:MI:SS'), 'IFN');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (4, 'CONDICION', 'CONDICION', 'C', 'C', 'S', TO_DATE('10/20/2015 11:08:49', 'MM/DD/YYYY HH24:MI:SS'), 'IFN', TO_DATE('10/20/2015 11:08:49', 'MM/DD/YYYY HH24:MI:SS'), 'IFN');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (5, 'FORMA FUSTE', 'FORMA FUSTE', 'C', 'C', 'S', TO_DATE('10/20/2015 11:08:49', 'MM/DD/YYYY HH24:MI:SS'), 'IFN', TO_DATE('10/20/2015 11:08:49', 'MM/DD/YYYY HH24:MI:SS'), 'IFN');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (6, 'DAÑOS', 'DAÑOS', 'C', 'C', 'S', TO_DATE('10/20/2015 11:08:49', 'MM/DD/YYYY HH24:MI:SS'), 'IFN', TO_DATE('10/20/2015 11:08:49', 'MM/DD/YYYY HH24:MI:SS'), 'IFN');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (7, 'EQUIPOS 1 PARA MEDICION DE DIAMETROS', 'EQUIPOS 1 PARA MEDICION DE DIAMETROS', 'C', 'C', 'S', TO_DATE('10/20/2015 11:08:49', 'MM/DD/YYYY HH24:MI:SS'), 'IFN', TO_DATE('10/20/2015 11:08:49', 'MM/DD/YYYY HH24:MI:SS'), 'IFN');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (8, 'EQUIPOS 2 PARA MEDICION DE ALTURAS', 'EQUIPOS 2 PARA MEDICION DE ALTURAS', 'C', 'C', 'S', TO_DATE('10/20/2015 11:08:49', 'MM/DD/YYYY HH24:MI:SS'), 'IFN', TO_DATE('10/20/2015 11:08:49', 'MM/DD/YYYY HH24:MI:SS'), 'IFN');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (9, 'SI/NO', 'SI/NO', 'C', 'C', 'S', TO_DATE('10/20/2015 11:12:44', 'MM/DD/YYYY HH24:MI:SS'), 'IFN', TO_DATE('10/20/2015 11:12:44', 'MM/DD/YYYY HH24:MI:SS'), 'IFN');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (10, 'TIPO DETRITO', 'TIPO DETRITO', 'C', 'C', 'S', TO_DATE('10/20/2015 11:12:44', 'MM/DD/YYYY HH24:MI:SS'), 'IFN', TO_DATE('10/20/2015 11:12:44', 'MM/DD/YYYY HH24:MI:SS'), 'IFN');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (11, 'TIPO INDIVIDUO', 'TIPO INDIVIDUO', 'C', 'C', 'S', TO_DATE('05/18/2016 10:16:28', 'MM/DD/YYYY HH24:MI:SS'), 'IFN', TO_DATE('05/18/2016 10:16:28', 'MM/DD/YYYY HH24:MI:SS'), 'IFN');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (12, 'IND_O_FUSTE', 'INDIVIDUO O FUSTE', 'C', 'C', 'S', TO_DATE('06/02/2017 14:06:30', 'MM/DD/YYYY HH24:MI:SS'), 'SYS', TO_DATE('06/02/2017 14:06:30', 'MM/DD/YYYY HH24:MI:SS'), 'SYS');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (13, 'TIPO TALLO', 'TIPO TALLO', 'C', 'C', 'S', TO_DATE('06/02/2017 14:06:30', 'MM/DD/YYYY HH24:MI:SS'), 'SYS', TO_DATE('06/02/2017 14:06:30', 'MM/DD/YYYY HH24:MI:SS'), 'SYS');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (14, 'TIPO FUSTE PPERMANENTE', 'TIPO FUSTE PPERMANENTE', 'C', 'C', 'S', TO_DATE('06/12/2017 15:19:35', 'MM/DD/YYYY HH24:MI:SS'), 'SYS', TO_DATE('06/12/2017 15:19:35', 'MM/DD/YYYY HH24:MI:SS'), 'SYS');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (15, 'TIPO BRIGADA', 'TIPO BRIGADA', 'C', 'C', 'S', TO_DATE('06/12/2017 15:19:35', 'MM/DD/YYYY HH24:MI:SS'), 'SYS', TO_DATE('06/12/2017 15:19:35', 'MM/DD/YYYY HH24:MI:SS'), 'SYS');
Insert into IFN.IFN_LISTAS
   (ID_ARGUMENTO, NOMBRE, DESCRIPCION, TIPO_ARGUMENTO, FORMATO_ARGUMENTO, INDICADOR_PUBLICACION, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
 Values
   (16, 'TIPO RENDIMIENTO', 'TIPO RENDIMIENTO', 'C', 'C', 'S', TO_DATE('06/12/2017 15:19:35', 'MM/DD/YYYY HH24:MI:SS'), 'SYS', TO_DATE('06/12/2017 15:19:35', 'MM/DD/YYYY HH24:MI:SS'), 'SYS');
COMMIT;
